Fix linux commands

diff --git a/cmds/postinstall b/cmds/postinstall
--- a/cmds/postinstall
+++ b/cmds/postinstall
@@ -5,13 +5,22 @@ case `uname` in
     *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
 esac
 
-if [ -x "$basedir/node" ]; then
-  "$basedir/node"  "$basedir/../node_modules/bower/bin/bower" "install"
-  "$basedir/node"  "$basedir/../node_modules/tsd/build/cli.js" "reinstall" "-so"
-  ret=$?
+if [ -x $(which bower) ]; then
+	bower install
 else
-  node  "$basedir/../node_modules/bower/bin/bower" "install"
-  node  "$basedir/../node_modules/tsd/build/cli.js" "reinstall" "-so"
-  ret=$?
+	node "$basedir/../node_modules/bower/bin/bower" "install"
+
 fi
-exit $ret
+
+# If bower has failed - exit
+if [ $? -ne 0 ] ; then
+	exit $?
+fi
+
+if [ -x $(which tsd) ] ; then
+	tsd reinstall -so
+else
+	node "$basedir/../node_modules/tsd/build/cli.js" "reinstall" "-so"
+fi
+
+exit $?
